// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rttyzresokhdpsehjjmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dHl6cmVzb2toZHBzZWhqam1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTQ2NzQsImV4cCI6MjA2Njg3MDY3NH0.y2vbBOvjd_M7pHhnGi6oG6ykV35r1i6g--ZNHscBraI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});